### ISSUE TITLE
What's the unit of area being calculated in S2Cell class?

### ISSUE THREAD

**Issue by chhabraamit** [google/s2-geometry-library-java#9]
Level 0's average area is 2.0943951023931953 and 4 times of it is supposed to cover the entire Earth's area.

**Comment by placz** [comment]
It's measuring the surface area on a unit sphere covered by the cell. 6 times a level 0's average area is 4 * pi. (6 sides on a cube, not 4)

**Comment by datamacgyver** [comment]
To add context here (because I got here and scratched my head for a bit):

* S2 assumes the earth is a perfect sphere
* The surface area of a sphere is given by `4*pi*radius`. 
* If we assume radius is 1 ("a unit") then the surface area of a sphere is simply `4*pi`, or `12.5664...` 
* Note that `12.5664 / 6 (the six sides of the cube!) = 2.0944...` *which is the number you have*
* As we've not got a unit for our radius of one, our number also has no unit so in answer to your explicit question: There isn't one!

Now, your implicit question of how we obtain something that we can interpret more easily:
* I know that the total area of one cube face [given by S2's authors](https://s2geometry.io/resources/s2cell_statistics.html) is `85,011,012.19 km^2`
* If `2.0944... = 85,011,012.19` then `1 = 40,589,768.4219...` km
* Therefore, to convert to km^2 I multiply an S2 area by `40,589,768.4219...`
* I have not validated the accuracy of this compared to a projection of a polygon but it's certainly in the ballpark based on me drawing squares over the middle east. 

Please correct me if I'm wrong, this makes sense in my head. Oh, and **I've been liberal on the rounding here!** Your mileage will vary but I'd advise working the above out to a precision that fits your use case!

**Comment by eengle** [comment]
The unit of measure, when the sphere is radius 1, is called a "steradian", basically the spherical equivalent of the 2D radian. It has the nice property that a number 10% the size of the whole 4*pi value is in fact 10% of the land area, so it's linear with the size of the surface being covered.

**Comment by eengle** [comment]
I'm closing this but feel free to reopen if there are any other questions about this.
